name: "FR01 CASO DE NEGOCIO"
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: in_proyecto
    attributes:
      label: Proyecto
      description: "Ingresar el nombre completo del proyecto"
      placeholder: "Portal de Proveedores V1"
    validations:
      required: true  
  - type: input
    id: in_director
    attributes:
      label: Director de Proyecto
      description: "Ingresar el nombre completo del Director del Proyecto."
      placeholder: "Jose Carlos Torres Salas"
    validations:
      required: true
  - type: dropdown
    id: in_area_solicitante
    attributes:
      label: Area Solicitante
      description: "Seleccionar el area solicitante del proyecto."
      options:
        - Compras
        - Finanzas
        - OGI
    validations:
      required: true
  - type: textarea
    id: in_necesidad_problema
    attributes:
      label: Necesidad Social del Problema
      description: "Definir el problema, sus síntomas e identificar las causas principales que lo ocasionan, la necesidad de resolverlo y los principales stakeholders impactados."
    validations:
      required: true
  - type: textarea
    id: in_servicio
    attributes:
      label: Servicio
      description: "Descripción de la solución proporcionada por el proyecto indicando los principales entregables a alto nivel."
    validations:
      required: true
  - type: textarea
    id: in_valor_propuesta
    attributes:
      label: Valor Publico, Propuesta de Valor
      description: "Valor público (abarca tres perspectivas orientas al usuario o beneficiario)"
    validations:
      required: true
 - type: textarea
    id: in_relevancia
    attributes:
      label: Relevancia de la Estrategia
      description: "Destacar algo del procedimiento dispuesto para la toma de decisiones y/o para accionar frente a un determinado escenario"
    validations:
      required: true
 - type: textarea
    id: in_beneficiarios
    attributes:
      label: Benegiciarios
      description: "Identificar aquellas personas o entidades que son los beneficiarios directos (internos) de los resultados del proyecto y que por lo general pertenece a la organización que patrocina el proyecto."
    validations:
      required: true
